# -*- coding: utf-8 -*-
"""전기차프로젝트.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D_H_6A4f3AHhuXhAy8Ys5R2Hd1p8rznm
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# <Step1. 탐색> 데이터의 기초 정보 살펴보기"
   ]
  }
1. 설치 현황, 전기차 충전소 정보
"""

import csv
import pandas as pd
import folium

df_isnull = pd.read_csv('/content/전기자동차_위도경도.csv',  encoding = 'cp949')
df = df_isnull.dropna(how='any', axis = 0)
print(df)
smap = folium.Map(location=[36.437795 , 127.423688],titles="Stamen Terrian", zoom_start=8)

for name, lat, lng in zip(df.충전소명, df.위도, df.경도) :
  folium.Marker([lat, lng], popup=name).add_to(smap)
smap


"""2. 지역별 전기자동차 현황 """

import pandas as pd
import folium

df=pd.read_csv('/content/서울전기차대수.csv', encoding='cp949')#utf8 , cp949


print(df.head())
import requests
import json
import re

s_geo='https://raw.githubusercontent.com/southkorea/seoul-maps/master/kostat/2013/json/seoul_municipalities_geo_simple.json'

s_map = folium.Map(location=[37.559984,126.9753071],
                   tiles='Stamen Terrain', zoom_start=11)

folium.Choropleth(geo_data=s_geo, data=df, columns=['시군구명', '전기차수'], 
                  fill_color='YlOrRd', fill_opacity=0.7, line_opacity=0.3, 
                  threshold_scale=[0, 250, 500, 1000, 1500, 2000, 3000, 40000], 
                  key_on='feature.properties.name').add_to(s_map)

s_map

"""3. 지역별 전기자동차 수요 예측"""

