# -*- coding: utf-8 -*-
"""전기차프로젝트.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D_H_6A4f3AHhuXhAy8Ys5R2Hd1p8rznm

1,2 설치 현황, 전기차 충전소 정보
"""

import csv
import pandas as pd
import folium

df_isnull = pd.read_csv('/content/전기자동차_위도경도.csv',  encoding = 'cp949')
df = df_isnull.dropna(how='any', axis = 0)
print(df)
smap = folium.Map(location=[36.437795 , 127.423688],titles="Stamen Terrian", zoom_start=8)

for name, lat, lng in zip(df.충전소명, df.위도, df.경도) :
  folium.Marker([lat, lng], popup=name).add_to(smap)
smap

"""2. 지역별 설치 현황"""



"""3. 지역별 전기자동차 현황 """

import pandas as pd
import folium

df=pd.read_csv('/content/인천_전기자동차현황.csv', encoding='cp949')


print(df.head())
import requests
import json
import re

s_geo='SIDO_MAP_2022.json'

s_map = folium.Map(location=[37.559984,126.9753071],
                   tiles='Stamen Terrain', zoom_start=11)

folium.Choropleth(geo_data=s_geo, data=df, columns=['군구명', '합계'],
                  fill_color='YlOrRd', fill_opacity=0.7, line_opacity=0.3,
                  threshold_scale=[0, 250, 500, 1000, 1500, 2000, 3000, 40000],
                  key_on='feature.properties.name').add_to(s_map)

s_map

"""4. 지역별 전기자동차 수요 예측"""

